trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SONARNEW' # Replace with your service connection name
    organization: 'hammadbinmohd'       # From SonarCloud
    scannerMode: 'MSBuild'
    projectKey: 'hammadbinmohd_Assignment4'
    projectName: 'InversionCyclesWebApp'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100' # Use the version your project targets

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build project'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
