trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/Assignment4.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Assignment4.csproj'

- script: |
    curl -L -o dependency-check-12.1.0-release.zip https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
    unzip dependency-check-12.1.0-release.zip -d dependency-check
    chmod +x dependency-check/dependency-check/bin/dependency-check.sh
  displayName: 'Install OWASP Dependency Check'

- script: |
    ./dependency-check/dependency-check/bin/dependency-check.sh --project "Assignment4" --scan ./ --format "HTML" --out reports
  displayName: 'Run OWASP Dependency-Check'

- script: |
    echo "Listing contents for debugging:"
    ls -R
  displayName: 'Debug - List Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'reports'
    artifactName: 'DependencyScanReport'
