trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1) Restore
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 2) Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 3) Publish to a folder
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# 4) (Optional) Zip up the published output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

# 5) Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'         # your ARM service connection
    appType: 'webApp'
    appName: 'Flipsois'                # your actual App Service name
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
