trigger:
- main

variables:
  imageName: 'rotaswebapp'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: Install Docker

- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: 'login'
    containerRegistry: 'newcrassignment5'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'
    repository: '$(imageName)'

- task: Docker@2
  displayName: 'Push Image to ACR'
  inputs:
    command: 'push'
    tags: '$(Build.BuildId)'
    repository: '$(imageName)'
